version: 2
jobs:
    test:
        steps:
           - checkout
           - run: sudo add-apt-repository -y ppa:ondrej/php
           - run: sudo apt-get install php7.0
           - run: wget https://getcomposer.org/composer.phar
           - run: php7.0 composer.phar install
           - run: ./vendor/bin/phpunit
workflows:
  version: 2
  test:
    jobs:
      - test