version: 2
jobs:
    test:
        docker:
          image: circleci/php:7.0-node-browsers
        machine:
          php:
            version: 7.0.31
        steps:
           - checkout
           - run: sudo composer self-update
           - run: composer install
           - run: ./vendor/bin/phpunit
workflows:
  version: 2
  test:
    jobs:
      - test