version: 2
jobs:
    test:
        docker:
            - image: circleci/php:7-apache-node-browsers
        steps:
           - checkout
           - run: sudo composer self-update
           - run: composer install
           - run: ./vendor/bin/phpunit -c ./phpunit.xml.dist
workflows:
  version: 2
  test:
    jobs:
      - test