version: 2
jobs:
    test:
        machine:
          php:
            version: 7.0.4
        dependencies:
          pre:
            - rm /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini
        steps:
           - checkout
           - run: sudo apt-get install wget -y
           - run: wget https://getcomposer.org/composer.phar
           - run: php composer.phar install
           - run: ./vendor/bin/phpunit
workflows:
  version: 2
  test:
    jobs:
      - test